openapi: 3.2.0
info:
  description: Description of all APIs
  title: Consolidate Services Account Service API
  version: version not set
tags:
- name: AccountService
paths:
  /api/v1/account:
    get:
      tags:
      - AccountService
      summary: ListAccounts returns the list of accounts
      operationId: AccountService_ListAccounts
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountAccountsList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/v1/account/can-i/{resource}/{action}/{subresource}:
    get:
      tags:
      - AccountService
      summary: CanI checks if the current account has permission to perform an action
      operationId: AccountService_CanI
      parameters:
      - name: resource
        in: path
        required: true
        schema:
          type: string
      - name: action
        in: path
        required: true
        schema:
          type: string
      - name: subresource
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountCanIResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/v1/account/password:
    put:
      tags:
      - AccountService
      summary: UpdatePassword updates an account's password to a new value
      operationId: AccountService_UpdatePassword
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountUpdatePasswordResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accountUpdatePasswordRequest'
        required: true
  /api/v1/account/{name}:
    get:
      tags:
      - AccountService
      summary: GetAccount returns an account
      operationId: AccountService_GetAccount
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountAccount'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/v1/account/{name}/token:
    post:
      tags:
      - AccountService
      summary: CreateToken creates a token
      operationId: AccountService_CreateToken
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountCreateTokenResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accountCreateTokenRequest'
        required: true
  /api/v1/account/{name}/token/{id}:
    delete:
      tags:
      - AccountService
      summary: DeleteToken deletes a token
      operationId: AccountService_DeleteToken
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountEmptyResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
components:
  schemas:
    accountCanIResponse:
      type: object
      properties:
        value:
          type: string
    accountToken:
      type: object
      properties:
        expiresAt:
          type: integer
          format: int64
        id:
          type: string
        issuedAt:
          type: integer
          format: int64
    accountCreateTokenResponse:
      type: object
      properties:
        token:
          type: string
    accountEmptyResponse:
      type: object
    runtimeError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
        error:
          type: string
        message:
          type: string
    accountCreateTokenRequest:
      type: object
      properties:
        expiresIn:
          type: integer
          format: int64
          title: expiresIn represents a duration in seconds
        id:
          type: string
        name:
          type: string
    accountUpdatePasswordResponse:
      type: object
    accountUpdatePasswordRequest:
      type: object
      properties:
        currentPassword:
          type: string
        name:
          type: string
        newPassword:
          type: string
    accountAccountsList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/accountAccount'
    accountAccount:
      type: object
      properties:
        capabilities:
          type: array
          items:
            type: string
        enabled:
          type: boolean
        name:
          type: string
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/accountToken'
    protobufAny:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
