openapi: 3.2.0
info:
  description: Description of all APIs
  title: Consolidate Services Notification Service API
  version: version not set
tags:
- name: Notification Service
paths:
  /api/v1/notifications/services:
    get:
      tags:
      - Notification Service
      summary: List returns list of services
      operationId: NotificationService_ListServices
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notificationServiceList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/v1/notifications/templates:
    get:
      tags:
      - Notification Service
      summary: List returns list of templates
      operationId: NotificationService_ListTemplates
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notificationTemplateList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/v1/notifications/triggers:
    get:
      tags:
      - Notification Service
      summary: List returns list of triggers
      operationId: NotificationService_ListTriggers
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notificationTriggerList'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
components:
  schemas:
    notificationServiceList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/notificationService'
    notificationTriggerList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/notificationTrigger'
    protobufAny:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
    runtimeError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
        error:
          type: string
        message:
          type: string
    notificationTrigger:
      type: object
      properties:
        name:
          type: string
    notificationService:
      type: object
      properties:
        name:
          type: string
    notificationTemplateList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/notificationTemplate'
    notificationTemplate:
      type: object
      properties:
        name:
          type: string
