openapi: 3.2.0
info:
  description: Description of all APIs
  title: Consolidate Services AccountService Session Service API
  version: version not set
tags:
- name: SessionService
paths:
  /api/v1/session:
    post:
      tags:
      - SessionService
      summary: Create a new JWT for authentication and set a cookie if using HTTP
      operationId: SessionService_Create
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionSessionResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sessionSessionCreateRequest'
        required: true
    delete:
      tags:
      - SessionService
      summary: Delete an existing JWT cookie if using HTTP
      operationId: SessionService_Delete
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionSessionResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
  /api/v1/session/userinfo:
    get:
      tags:
      - SessionService
      summary: Get the current user's info
      operationId: SessionService_GetUserInfo
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionGetUserInfoResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
components:
  schemas:
    sessionSessionResponse:
      description: SessionResponse wraps the created token or returns an empty string if deleted.
      type: object
      properties:
        token:
          type: string
    sessionSessionCreateRequest:
      description: SessionCreateRequest is for logging in.
      type: object
      properties:
        password:
          type: string
        token:
          type: string
        username:
          type: string
    sessionGetUserInfoResponse:
      type: object
      title: The current user's userInfo info
      properties:
        groups:
          type: array
          items:
            type: string
        iss:
          type: string
        loggedIn:
          type: boolean
        username:
          type: string
    runtimeError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
        error:
          type: string
        message:
          type: string
    protobufAny:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
