swagger: '2.0'
info:
  description: Description of all APIs
  title: Consolidate Services AccountService RepoCredsService API
  version: version not set
consumes:
- application/json
produces:
- application/json
tags:
- name: RepoCredsService
paths:
  /api/v1/repocreds:
    get:
      tags:
      - RepoCredsService
      summary: ListRepositoryCredentials gets a list of all configured repository credential sets
      operationId: RepoCredsService_ListRepositoryCredentials
      parameters:
      - type: string
        description: Repo URL for query.
        name: url
        in: query
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/v1alpha1RepoCredsList'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
    post:
      tags:
      - RepoCredsService
      summary: CreateRepositoryCredentials creates a new repository credential set
      operationId: RepoCredsService_CreateRepositoryCredentials
      parameters:
      - description: Repository definition
        name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/v1alpha1RepoCreds'
      - type: boolean
        description: Whether to create in upsert mode.
        name: upsert
        in: query
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/v1alpha1RepoCreds'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
  /api/v1/repocreds/{creds.url}:
    put:
      tags:
      - RepoCredsService
      summary: UpdateRepositoryCredentials updates a repository credential set
      operationId: RepoCredsService_UpdateRepositoryCredentials
      parameters:
      - type: string
        description: URL is the URL to which these credentials match
        name: creds.url
        in: path
        required: true
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/v1alpha1RepoCreds'
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/v1alpha1RepoCreds'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
  /api/v1/repocreds/{url}:
    delete:
      tags:
      - RepoCredsService
      summary: DeleteRepositoryCredentials deletes a repository credential set from the configuration
      operationId: RepoCredsService_DeleteRepositoryCredentials
      parameters:
      - type: string
        name: url
        in: path
        required: true
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/repocredsRepoCredsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
  /api/v1/write-repocreds:
    get:
      tags:
      - RepoCredsService
      summary: ListWriteRepositoryCredentials gets a list of all configured repository credential sets that have write access
      operationId: RepoCredsService_ListWriteRepositoryCredentials
      parameters:
      - type: string
        description: Repo URL for query.
        name: url
        in: query
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/v1alpha1RepoCredsList'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
    post:
      tags:
      - RepoCredsService
      summary: CreateWriteRepositoryCredentials creates a new repository credential set with write access
      operationId: RepoCredsService_CreateWriteRepositoryCredentials
      parameters:
      - description: Repository definition
        name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/v1alpha1RepoCreds'
      - type: boolean
        description: Whether to create in upsert mode.
        name: upsert
        in: query
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/v1alpha1RepoCreds'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
  /api/v1/write-repocreds/{creds.url}:
    put:
      tags:
      - RepoCredsService
      summary: UpdateWriteRepositoryCredentials updates a repository credential set with write access
      operationId: RepoCredsService_UpdateWriteRepositoryCredentials
      parameters:
      - type: string
        description: URL is the URL to which these credentials match
        name: creds.url
        in: path
        required: true
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/v1alpha1RepoCreds'
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/v1alpha1RepoCreds'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
  /api/v1/write-repocreds/{url}:
    delete:
      tags:
      - RepoCredsService
      summary: DeleteWriteRepositoryCredentials deletes a repository credential set with write access from the configuration
      operationId: RepoCredsService_DeleteWriteRepositoryCredentials
      parameters:
      - type: string
        name: url
        in: path
        required: true
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/repocredsRepoCredsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/runtimeError'
definitions:
  protobufAny:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  v1ListMeta:
    description: 'ListMeta describes metadata that synthetic resources must have, including lists and

      various status objects. A resource may have only one of {ObjectMeta, ListMeta}.'
    type: object
    properties:
      continue:
        description: 'continue may be set if the user set a limit on the number of items returned, and indicates that

          the server has more data available. The value is opaque and may be used to issue another request

          to the endpoint that served this list to retrieve the next set of available objects. Continuing a

          consistent list may not be possible if the server configuration has changed or more than a few

          minutes have passed. The resourceVersion field returned when using this continue value will be

          identical to the value in the first response, unless you have received this token from an error

          message.'
        type: string
      remainingItemCount:
        type: integer
        format: int64
        title: 'remainingItemCount is the number of subsequent items in the list which are not included in this

          list response. If the list request contained label or field selectors, then the number of

          remaining items is unknown and the field will be left unset and omitted during serialization.

          If the list is complete (either because it is not chunking or because this is the last chunk),

          then there are no more remaining items and this field will be left unset and omitted during

          serialization.

          Servers older than v1.15 do not set this field.

          The intended use of the remainingItemCount is *estimating* the size of a collection. Clients

          should not rely on the remainingItemCount to be set or to be exact.

          +optional'
      resourceVersion:
        type: string
        title: 'String that identifies the server''s internal version of this object that

          can be used by clients to determine when objects have changed.

          Value must be treated as opaque by clients and passed unmodified back to the server.

          Populated by the system.

          Read-only.

          More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency

          +optional'
      selfLink:
        type: string
        title: 'Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.

          +optional'
  runtimeError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      error:
        type: string
      message:
        type: string
  repocredsRepoCredsResponse:
    type: object
    title: RepoCredsResponse is a response to most repository credentials requests
  v1alpha1RepoCreds:
    type: object
    title: RepoCreds holds the definition for repository credentials
    properties:
      azureActiveDirectoryEndpoint:
        type: string
        title: AzureActiveDirectoryEndpoint specifies the Azure Active Directory endpoint used for Service Principal authentication. If empty will default to https://login.microsoftonline.com
      azureServicePrincipalClientId:
        type: string
        title: AzureServicePrincipalClientId specifies the client ID of the Azure Service Principal used to access the repo
      azureServicePrincipalClientSecret:
        type: string
        title: AzureServicePrincipalClientSecret specifies the client secret of the Azure Service Principal used to access the repo
      azureServicePrincipalTenantId:
        type: string
        title: AzureServicePrincipalTenantId specifies the tenant ID of the Azure Service Principal used to access the repo
      bearerToken:
        type: string
        title: BearerToken contains the bearer token used for Git BitBucket Data Center auth at the repo server
      enableOCI:
        type: boolean
        title: EnableOCI specifies whether helm-oci support should be enabled for this repo
      forceHttpBasicAuth:
        type: boolean
        title: ForceHttpBasicAuth specifies whether Argo CD should attempt to force basic auth for HTTP connections
      gcpServiceAccountKey:
        type: string
        title: GCPServiceAccountKey specifies the service account key in JSON format to be used for getting credentials to Google Cloud Source repos
      githubAppEnterpriseBaseUrl:
        type: string
        title: GithubAppEnterpriseBaseURL specifies the GitHub API URL for GitHub app authentication. If empty will default to https://api.github.com
      githubAppID:
        type: integer
        format: int64
        title: GithubAppId specifies the Github App ID of the app used to access the repo for GitHub app authentication
      githubAppInstallationID:
        type: integer
        format: int64
        title: GithubAppInstallationId specifies the ID of the installed GitHub App for GitHub app authentication
      githubAppPrivateKey:
        type: string
        title: GithubAppPrivateKey specifies the private key PEM data for authentication via GitHub app
      insecureOCIForceHttp:
        description: InsecureOCIForceHttp specifies whether the connection to the repository uses TLS at _all_. If true, no TLS. This flag is applicable for OCI repos only.
        type: boolean
      noProxy:
        type: string
        title: NoProxy specifies a list of targets where the proxy isn't used, applies only in cases where the proxy is applied
      password:
        type: string
        title: Password for authenticating at the repo server
      proxy:
        type: string
        title: Proxy specifies the HTTP/HTTPS proxy used to access repos at the repo server
      sshPrivateKey:
        type: string
        title: SSHPrivateKey contains the private key data for authenticating at the repo server using SSH (only Git repos)
      tlsClientCertData:
        type: string
        title: TLSClientCertData specifies the TLS client cert data for authenticating at the repo server
      tlsClientCertKey:
        type: string
        title: TLSClientCertKey specifies the TLS client cert key for authenticating at the repo server
      type:
        description: Type specifies the type of the repoCreds. Can be either "git", "helm" or "oci". "git" is assumed if empty or absent.
        type: string
      url:
        type: string
        title: URL is the URL to which these credentials match
      useAzureWorkloadIdentity:
        type: boolean
        title: UseAzureWorkloadIdentity specifies whether to use Azure Workload Identity for authentication
      username:
        type: string
        title: Username for authenticating at the repo server
  v1alpha1RepoCredsList:
    description: RepositoryList is a collection of Repositories.
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/v1alpha1RepoCreds'
      metadata:
        $ref: '#/definitions/v1ListMeta'
