openapi: 3.2.0
info:
  description: Description of all APIs
  title: Consolidate Services AccountService Version Service API
  version: version not set
tags:
- name: VersionService
paths:
  /api/version:
    get:
      tags:
      - VersionService
      summary: Version returns version information of the API server
      operationId: VersionService_Version
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versionVersionMessage'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeError'
components:
  schemas:
    runtimeError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
        error:
          type: string
        message:
          type: string
    versionVersionMessage:
      type: object
      title: VersionMessage represents version of the Argo CD API server
      properties:
        BuildDate:
          type: string
        Compiler:
          type: string
        ExtraBuildInfo:
          type: string
        GitCommit:
          type: string
        GitTag:
          type: string
        GitTreeState:
          type: string
        GoVersion:
          type: string
        HelmVersion:
          type: string
        JsonnetVersion:
          type: string
        KubectlVersion:
          type: string
        KustomizeVersion:
          type: string
        Platform:
          type: string
        Version:
          type: string
    protobufAny:
      type: object
      properties:
        type_url:
          type: string
        value:
          type: string
          format: byte
